[package]
name = "the_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30"
anchor-spl = "0.30"
solana-program = "1.18"

[lib]
crate-type = ["cdylib", "lib"]
name = "the_vault"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
